@extends('layouts.admin')

@section('title', 'New Category')

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('admin.categories.index') }}">Admin</a></li>
    <li class="breadcrumb-item"><a href="{{ route('admin.categories.index') }}">Categories</a></li>
    <li class="breadcrumb-item active">New</li>
@endsection

@section('content')
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1 class="h3 mb-0">New Category</h1>
    </div>

    <div class="card" style="max-width: 700px;">
        <div class="card-body">
            <form action="{{ route('admin.categories.store') }}" method="POST">
                @csrf

                <div class="mb-3">
                    <label for="name" class="form-label">Name</label>
                    <input type="text" id="name" name="name" value="{{ old('name') }}" class="form-control" required placeholder="e.g. Getting Started">
                </div>

                <div class="mb-3">
                    <label for="slug" class="form-label">Slug</label>
                    <input type="text" id="slug" name="slug" value="{{ old('slug') }}" class="form-control" placeholder="auto-generated from name">
                </div>

                <div class="mb-3">
                    <label for="description" class="form-label">Description</label>
                    <textarea id="description" name="description" class="form-control" rows="3" placeholder="Brief description of this category...">{{ old('description') }}</textarea>
                </div>

                <div class="mb-3">
                    <label for="icon" class="form-label">Icon</label>
                    <input type="text" id="icon" name="icon" value="{{ old('icon') }}" class="form-control" placeholder="e.g. rocket-takeoff (Bootstrap Icons name)">
                    <div class="form-text">Use <a href="https://icons.getbootstrap.com/" target="_blank">Bootstrap Icons</a> name without the "bi-" prefix.</div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label for="color" class="form-label">Color</label>
                            <input type="color" id="color" name="color" value="{{ old('color', '#E8571A') }}" class="form-control form-control-color" title="Choose category color">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label for="sort_order" class="form-label">Sort Order</label>
                            <input type="number" id="sort_order" name="sort_order" value="{{ old('sort_order', 0) }}" class="form-control" min="0">
                        </div>
                    </div>
                </div>

                <div class="mb-3">
                    <label for="group" class="form-label">Group</label>
                    <select id="group" name="group" class="form-select">
                        <option value="">-- Select Group --</option>
                        <option value="getting-started" {{ old('group') === 'getting-started' ? 'selected' : '' }}>Getting Started</option>
                        <option value="infrastructure" {{ old('group') === 'infrastructure' ? 'selected' : '' }}>Infrastructure</option>
                        <option value="advanced" {{ old('group') === 'advanced' ? 'selected' : '' }}>Advanced</option>
                        <option value="resources" {{ old('group') === 'resources' ? 'selected' : '' }}>Resources</option>
                    </select>
                </div>

                <div class="d-flex gap-2 mt-4 pt-3 border-top">
                    <button type="submit" class="btn btn-primary">Create Category</button>
                    <a href="{{ route('admin.categories.index') }}" class="btn btn-outline-secondary">Cancel</a>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        // Auto-generate slug from name
        const nameInput = document.getElementById('name');
        const slugInput = document.getElementById('slug');

        nameInput.addEventListener('input', function() {
            if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
                slugInput.value = this.value
                    .toLowerCase()
                    .replace(/[^a-z0-9]+/g, '-')
                    .replace(/-$/, '');
                slugInput.dataset.autoGenerated = 'true';
            }
        });

        slugInput.addEventListener('input', function() {
            this.dataset.autoGenerated = 'false';
        });
    </script>
@endpush
